import os

def generate_index_html():
  # Directorios a ignorar
  ignored_dirs = {'lib', 'fonts', 'dist', 'node_modules', 'public'}
  
  html = [
    '<!DOCTYPE html>',
    '<html lang="es">',
    '<head>',
    '  <meta charset="UTF-8">',
    '  <meta name="viewport" content="width=device-width, initial-scale=1.0">',
    '  <title>Presentaciones</title>',
    '  <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@1.*/css/pico.min.css">',
    '  <style>',
    '    .local-presentation {',
    '      margin-top: 2rem;',
    '      padding: 1rem;',
    '      border: 1px solid var(--primary);',
    '      border-radius: 0.5rem;',
    '    }',
    '    .local-presentation h2 {',
    '      margin-top: 0;',
    '    }',
    '    .info-message {',
    '      margin: 1rem 0;',
    '      padding: 1rem;',
    '      background-color: var(--primary);',
    '      border-radius: 0.5rem;',
    '      font-size: 0.9rem;',
    '      color: white;',
    '    }',
    '    .info-message strong {',
    '      color: #000000;',
    '    }',
    '    .info-message-text {',
    '      color: white;',
    '    }',
    '    #submitButton {',
    '      display: none;',
    '    }',
    '    .folder-selected #submitButton {',
    '      display: block;',
    '    }',
    '  </style>',
    '</head>',
    '<body>',
    '  <main class="container">',
    '    <h1>Presentaciones</h1>',
    '    ',
    '    <div class="local-presentation">',
    '      <h2>Cargar Presentación Local</h2>',
    '      <div class="info-message">',
    '        <p class="info-message-text">⚠️ <strong>Importante:</strong> Los archivos se procesan localmente en tu navegador y no se suben a ningún servidor. La presentación se mostrará usando los archivos de tu carpeta local.</p>',
    '      </div>',
    '      <form id="localForm">',
    '        <label for="localFolder">',
    '          Selecciona la carpeta de la presentación',
    '          <input type="file" id="localFolder" webkitdirectory directory multiple>',
    '        </label>',
    '        <button type="submit" id="submitButton">Cargar Presentación</button>',
    '      </form>',
    '    </div>',
    '    ',
    '    <h2>Presentaciones Disponibles</h2>',
    '    <ul id="presentationsList">',
  ]

  for folder in sorted(os.listdir('.')):
    if folder.startswith('.') or not os.path.isdir(folder) or folder in ignored_dirs:
      continue

    # Verifica si existe el archivo contenidos.md o content.md
    if os.path.exists(os.path.join(folder, 'contenidos.md')) or os.path.exists(os.path.join(folder, 'content.md')):
      # Enlaza a presentacion.html pasando el directorio como parámetro
      label = f"{folder}"
      html.append(f'      <li><a href="presentacion.html?presentacion={label}">{label}</a></li>')

  html += [
    '    </ul>',
    '  </main>',
    '  ',
    '  <script>',
    '    // Manejar el formulario de carga local',
    '    const form = document.getElementById("localForm");',
    '    const folderInput = document.getElementById("localFolder");',
    '    ',
    '    folderInput.addEventListener("change", () => {',
    '      if (folderInput.files.length > 0) {',
    '        // Verificar si existe contenidos.md',
    '        let hasContents = false;',
    '        for (const file of folderInput.files) {',
    '          if (file.name === "contenidos.md") {',
    '            hasContents = true;',
    '            break;',
    '          }',
    '        }',
    '        ',
    '        if (hasContents) {',
    '          form.classList.add("folder-selected");',
    '        } else {',
    '          alert("La carpeta seleccionada no contiene un archivo contenidos.md");',
    '          folderInput.value = "";',
    '          form.classList.remove("folder-selected");',
    '        }',
    '      } else {',
    '        form.classList.remove("folder-selected");',
    '      }',
    '    });',
    '    ',
    '    form.addEventListener("submit", async (e) => {',
    '      e.preventDefault();',
    '      const files = folderInput.files;',
    '      ',
    '      if (files.length === 0) {',
    '        alert("Por favor, selecciona una carpeta");',
    '        return;',
    '      }',
    '      ',
    '      // Obtener el nombre de la carpeta seleccionada',
    '      const basePath = files[0].webkitRelativePath.split("/")[0];',
    '      ',
    '      // Guardar los archivos en sessionStorage',
    '      for (const file of files) {',
    '        const reader = new FileReader();',
    '        reader.onload = (e) => {',
    '          // Guardar la ruta relativa completa como clave',
    '          const relativePath = file.webkitRelativePath;',
    '          // Si es una imagen, usar readAsDataURL, si no, usar readAsText',
    '          if (file.type.startsWith("image/")) {',
    '            sessionStorage.setItem(`local_${relativePath}`, e.target.result);',
    '          } else {',
    '            sessionStorage.setItem(`local_${relativePath}`, e.target.result);',
    '          }',
    '          console.log("Guardado en sessionStorage:", `local_${relativePath}`);',
    '        };',
    '        // Usar readAsDataURL para imágenes y readAsText para el resto',
    '        if (file.type.startsWith("image/")) {',
    '          reader.readAsDataURL(file);',
    '        } else {',
    '          reader.readAsText(file);',
    '        }',
    '      }',
    '      ',
    '      // Redirigir a la presentación',
    '      window.location.href = `presentacion.html?presentacion=local_${basePath}`;',
    '    });',
    '  </script>',
    '</body>',
    '</html>'
  ]

  with open("index.html", "w", encoding="utf-8") as f:
    f.write("\n".join(html))
  print("✅ index.html generado con éxito.")

if __name__ == "__main__":
  generate_index_html()
